version: '3.9'
name: auth_service
services:
  app:
    container_name: auth_service_app
    image: auth_service:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "python manage.py migrate
      && gunicorn --workers=3 --timeout=600 --bind=0.0.0.0:8000 core.wsgi:application"
    depends_on:
      - postgres
      - redis
      - celery
    env_file:
      - .compose/config.env
    networks:
      - auth_service
    ports:
      - "8000:8000"
    restart: always

  redis:
    container_name: auth_service_redis
    image: redis:7.2
    command: [ "redis-server", "--requirepass", "redis_password" ]
    networks:
      - auth_service
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data

  postgres:
    container_name: auth_service_postgres
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_service
    networks:
      - auth_service
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

  celery:
    container_name: auth_service_celery
    image: auth_service:latest
    build:
      context: .
      dockerfile: Dockerfile.local
    command: bash -c "celery -A core.celery worker -l INFO"
    depends_on:
      - postgres
      - redis
    env_file:
      - .compose/config.env
    networks:
      - auth_service
    restart: always


networks:
  auth_service:
    driver: bridge

volumes:
  postgres-data:
  redis-data: